version: "3.8"

services:
    backend:
        build:
            context: ./backend
        ports:
            - "5000:5000"
        restart: always
        environment:
            - APP_ENVIRONMENT=debug
            - APP_VERSION=0.1.0
        healthcheck:
            test: curl --fail http://localhost:5000/health || exit 1
            start_period: 10s
            interval: 60s
            retries: 5
            timeout: 10s
