version: "3.8"

services:
    backend:
        image: patr1ick/green-web-analyzer:backend-latest
        container_name: green-web-analyzer-backend
        network_mode: host
        ports:
            - "5000:5000"
        restart: always
        environment:
            - APP_ENVIRONMENT=prod
            - APP_VERSION=${BACKEND_VERSION}
        healthcheck:
            test: curl --fail http://localhost:5000/health || exit 1
            start_period: 10s
            interval: 60s
            retries: 5
            timeout: 10s

    frontend:
        image: patr1ick/green-web-analyzer:frontend-latest
        container_name: green-web-analyzer-frontend
        network_mode: host
        ports:
            - "443:443"
        restart: always
        environment:
            - WEBHOOK_PASSWORD=
        volumes:
            - ~/caddy_data:/data
            - ~/caddy_config:/config
