version: "3.8"

services:
    backend:
        image: green-web-analyzer-backend:latest
        ports:
            - "5000:5000"
        restart: always
        environment:
            - APP_ENVIRONMENT=prod
            - APP_VERSION=${BACKEND_VERSION}

    frontend:
        image: green-web-analyzer-frontend:latest
        ports:
            - "443:443"
        restart: always
