version: "3.8"

services:
    backend:
        image: patr1ick/green-web-analyzer:backend-latest
        container_name: green-web-analyzer-backend
        network_mode: host
        ports:
            - "5000:5000"
        restart: always
        environment:
            - APP_ENVIRONMENT=prod
            - APP_VERSION=${BACKEND_VERSION}

    frontend:
        image: patr1ick/green-web-analyzer:frontend-latest
        container_name: green-web-analyzer-frontend
        network_mode: host
        ports:
            - "443:443"
        restart: always
        volumes:
            - ~/caddy_data:/data
            - ~/caddy_config:/config
