name: deployment

on:
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build and push docker images
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build fronted
        run: |
          cd frontend
          npm run build
          cd ..
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: |
            patr1ick/green-web-analyzer:${{ push tag }}
            patr1ick/green-web-analyzer:latest
      
      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: |
            patr1ick/green-web-analyzer:${{ tag }}
            patr1ick/green-web-analyzer:latest
      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            patr1ick/green-web-analyzer:${{ tag }}
            patr1ick/green-web-analyzer:latest
          
  deploy:
    name: Deploy to server
    runs-on: self-hosted
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{"backend_version": ${{ tag }} }'
