name: deployment

on:
    push:
        tags:
            - "*"
    schedule:
        - cron: 0 1 1 * *

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        name: Build images and push to registry
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Set env
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
            - name: Build fronted
              run: |
                  cd frontend
                  npm install
                  npm run build
                  cd ..
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push backend image
              uses: docker/build-push-action@v3
              with:
                  context: ./backend
                  push: true
                  tags: |
                      patr1ick/green-web-analyzer-backend:${{ env.RELEASE_VERSION }}
                      patr1ick/green-web-analyzer-backend:latest

            - name: Build and push frontend image
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./frontend/caddy/Dockerfile
                  push: true
                  tags: |
                      patr1ick/green-web-analyzer-gui:${{ env.RELEASE_VERSION }}
                      patr1ick/green-web-analyzer-gui:latest

    deploy:
        name: Deploy to cluster
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - uses: azure/setup-kubectl@v3
          - uses: azure/k8s-set-context@v3
            with:
              method: kubeconfig
              kubeconfig: ${{ secrets.KUBECONFIG }}
          - name: Deploy backend
            uses: Azure/k8s-deploy@v4
            with:
              action: deploy
              namespace: 'green-web-analyzer'
              manifests: |
                ./backend/k8s/backend-deployment.yaml
                ./backend/k8s/backend-ingress.yaml
          - name: Deploy frontend
            uses: Azure/k8s-deploy@v4
            with:
              action: deploy
              namespace: 'green-web-analyzer'
              manifests: |
                ./frontend/caddy/k8s-deployment.yaml
                ./frontend/caddy/k8s-ingress.yaml
